### ISSUE TITLE
No works

### ISSUE THREAD

**Issue by osobrevilla** [rodrigopmatias/atom-flame#1]

**Comment by rodrigopmatias** [comment]
can you give me more details of what did not work?

**Comment by rodrigopmatias** [comment]
This is the result of theme

![atom-shot](https://cloud.githubusercontent.com/assets/109422/11411835/8887d8c0-93b3-11e5-825c-ad394d67b9cc.png)

**Comment by osobrevilla** [comment]
the installation did not work yesterday . I tried using other and if they worked . When he wanted to apply the theme did not apply . Now I just install it and it's okay . Thanks :D

**Comment by rodrigopmatias** [comment]
https://github.com/rodrigopmatias/ps-wagner
Em 25/11/2015 20:53, "Oscar Sobrevilla" <notifications@github.com> escreveu:

**Comment by rodrigopmatias** [comment]
Thank you for your feedback, will close the issue.
